# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10rWEFQqDCt5HMqs2CkfRKjPYum91TVjg
"""

# Simple Stock Tracker

# Hardcoded stock prices
stock_prices = {
    "AAPL": 180,
    "TSLA": 250,
    "GOOGL": 135,
    "AMZN": 120,
    "MSFT": 300
}

# Dictionary to store user input
portfolio = {}

# Input loop
while True:
    stock = input("Enter stock symbol (or type 'done' to finish): ").upper()
    if stock == 'DONE':
        break
    if stock not in stock_prices:
        print("Stock not in the list. Try again.")
        continue
    try:
        quantity = int(input(f"Enter quantity of {stock} shares: "))
        portfolio[stock] = portfolio.get(stock, 0) + quantity
    except ValueError:
        print("Invalid quantity. Try again.")

# Calculate total investment
total_value = 0
for stock, quantity in portfolio.items():
    price = stock_prices[stock]
    value = price * quantity
    total_value += value
    print(f"{stock}: {quantity} shares x ${price} = ${value}")

print(f"\nTotal Investment Value: ${total_value}")

# Optionally save to file
save = input("Do you want to save the result to a file? (yes/no): ").lower()
if save == 'yes':
    filename = input("Enter file name (with .txt or .csv extension): ")
    with open(filename, 'w') as f:
        f.write("Stock,Quantity,Price,Value\n")
        for stock, quantity in portfolio.items():
            price = stock_prices[stock]
            value = price * quantity
            f.write(f"{stock},{quantity},{price},{value}\n")
        f.write(f"\nTotal Investment Value: ${total_value}")
    print(f"Results saved to {filename}")