# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yOL0U4QHeBOmMMGXbzfLPyXv4zJj0IlN
"""

import random
words=['python','java','kotlin','javascripts','apple','blue','chess','carrom',
       'red','beans','book']
word=random.choice(words)
guessed=['_']*len(word)
tries=6
print("let's play hangman!")
print(' '.join(guessed))
while tries>0 and '_' in guessed:
  guess=input('guess a letter:').lower()
  if guess in word:
    for i,letter in enumerate(word):
      if letter==guess:
        guessed[i]=guess
  else:
    tries=tries-1
  print(" ".join(guessed))
  print(f"tries left:{tries}")
if '_' not in guessed:
  print(f"congratulations!, you've guessed the word:{word}")
else:
  print(f"game over!, the word was:{word}")